modLoader="javafml" #mandatory

loaderVersion="${loader_version_range}" #mandatory

license="${mod_license}"

[[mods]] #mandatory
    modId="${mod_id}" #mandatory
    version="${mod_version}" #mandatory
    displayName="${mod_name}" #mandatory
    authors="${mod_authors}" #optional
    description='''${mod_description}'''
    logoFile="icon.png"

[[mixins]]
    config="create_ss.mixins.json"

[[dependencies.${mod_id}]]
    modId="create"
    mandatory=true
    versionRange="[6.0.7,)"
    ordering="AFTER"
    side="BOTH"